F(TON_fnc_firstjoin,SERVER)
F(TON_fnc_fetchexperience,SERVER)
F(TON_fnc_saveexperienceserver,SERVER)
F(TON_fnc_firstexperience,SERVER)
F(life_fnc_firstjoin,CLIENT)
F(life_fnc_experienceReceived,CLIENT)